name: graphql-client
version: 1.2.1
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE.md
author:
  - Brandon Chinn <brandonchinn178@gmail.com>
maintainer:
  - Brandon Chinn <brandonchinn178@gmail.com>
category: Graphql
synopsis: A client for Haskell programs to query a GraphQL API
description: A client for Haskell programs to query a GraphQL API.
extra-source-files:
  - README.md
  - CHANGELOG.md
  # Make sure graphql-codegen-haskell.js is listed in the Cabal file,
  # in the off-chance it's not built yet
  - ./js/graphql-codegen-haskell.js
  - ./js/**/*

github: brandonchinn178/graphql-client

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.2.4.0 && < 3
    - aeson-schemas >= 1.3 && < 1.5
    - base >= 4.14 && < 5
    - http-client >= 0.5.13.1 && < 0.8
    - http-client-tls >= 0.3.5.3 && < 0.4
    - http-types >= 0.12.1 && < 0.13
    - mtl >= 2.2.2 && < 2.4
    - template-haskell >= 2.16 && < 3
    - text >= 1.2.3.0 && < 2.1
    - transformers >= 0.5.2.0 && < 0.7
    - unliftio-core >= 0.1.1.0 && < 0.3

executables:
  graphql-codegen:
    main: exe/Codegen.hs
    dependencies:
      - base >= 4.14 && < 5
      - bytestring >= 0.10.8.2 && < 0.12
      - file-embed >= 0.0.10.1 && < 0.1
      - graphql-client
      - optparse-applicative >= 0.14.2.0 && < 0.19
      - path >= 0.6.1 && < 0.10
      - path-io >= 1.3.3 && < 2
      - template-haskell >= 2.16 && < 3
      - typed-process >= 0.2.3.0 && < 0.3

tests:
  graphql-client-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson
      - aeson-schemas
      - base
      - graphql-client
      - mtl
      - tasty
      - tasty-hunit
